### PR TITLE
workWithSuperAdmin

### PR DESCRIPTION
**Pull request by MrNikaMilon**
As part of the work with the following branch: workWithSuperAdmin, these changes were made:
1. Two classes were created: SuperAdminService, SuperAdminRepositoryImpl and one interface: SuperAdminRepository
2. Created a method for adding objects of the class: addSuperAdminAccount

### CODE REVIEW

**Comment by MaksMusic** [comment]
in the SuperAdminRepositoryImpl class, make private fields AccountDatabase in the SuperAdminService class

**Comment by MrNikaMilon** [comment]
So, are you talking about an instance of the AccountDatabase class in SuperAdminRepositoryImpl and SuperAdminService or something else?

**Comment by MaksMusic** [comment]
> So, are you talking about an instance of the AccountDatabase class in SuperAdminRepositoryImpl and SuperAdminService or something else?

Yes,you heard correctly, Mr. Middle

**Comment by MrNikaMilon** [comment]
I'd really like to clarify the logic before we run my changes.  So we need to add a private instance of the AccountDatabase class to the following classes: 
1. SuperAdminRepositoryImpl.java 
2. SuperAdminService.java. 
But unfortunately I don't understand why we need to add a private field to a service class if in the service class we call a method from the impl where the method implements calling a private instance of the AccountDatabase class?

**Pull request closed without merging**
